---
# This playbook deploys the banking_shinhan app on FEP.


- hosts: local
  tasks:
    - name: Add, Commit, Push to git repository
      shell: cd ..; git add .; git commit -m 'update'; git push
      register: out
    - debug: var=out.stdout_lines
    - debug: var=out.stderr_lines

    - name: Pull git repository
      shell: cd ~/Documents/local-gs-generator && git pull https://gitkross31:git31\!%40%23@github.com/ninetydays/gs-generator.git
      args:
        executable: /bin/bash
      register: out
    - debug: var=out.stdout_lines
    - debug: var=out.stderr_lines

    - name: Install npm package
      shell: cd ~/Documents/local-gs-generator && npm i
      args:
        executable: /bin/bash
      register: out
    - debug: var=out.stdout_lines
    - debug: var=out.stderr_lines

    - name: Ensure pm2 is running
      shell: pm2 update
      args:
        executable: /bin/bash
      register: out
    - debug: var=out.stdout_lines
    - debug: var=out.stderr_lines

    - name: Restart pm2 module
      shell: pm2 restart local-gs-generator
      args:
        executable: /bin/bash
      register: out
    - debug: var=out.stdout_lines
    - debug: var=out.stderr_lines
